Tea 16
Aikeilol/team-project pull request #10
Opened 2024-01-22 16:30 UTC by Aikeilol

### Создать движок для змейки  на канвас

### 

### можно запустить спулив ветку командой yarn dev и нажать в хедере на раздел game

2024-01-22 17:23 UTC, zmenka reviewed
Я бы вынесла и разбила всю логику на методы, чтобы легче было ориентироваться. 

Еще случайно нашла баг, змейка не может доползти до самого левого края, и если там яблоко - не может его съесть)

<img width="409" alt="Screenshot 2024-01-22 at 18 03 39" src="https://github.com/Aikeilol/team-project/assets/5979721/d9727171-41b0-431c-982b-13e402753aab">

2024-01-22 17:23 UTC, zmenka commented on packages/client/src/pages/Game/index.tsx
> +  const snake: {
Давай вынесем в отдельный класс?

2024-01-22 17:23 UTC, zmenka commented on packages/client/src/pages/Game/index.tsx
> +  const apple = {
Давай вынесем в отдельный класс?

2024-01-22 17:23 UTC, zmenka commented on packages/client/src/pages/Game/index.tsx
> +      if (e.which === 37 && snake.dx === 0) {
можно использовать  поле code, там сразу понятные значение типа ArrowUp

2024-01-22 17:23 UTC, zmenka commented on packages/client/src/pages/Game/index.tsx
> +    return () => {
где-то не хватает cancelAnimationFrame

2024-01-22 17:23 UTC, zmenka commented on packages/client/src/pages/Game/index.tsx
> +  function getRandomInt(min: number, max: number) {
Давай вынесем в отдельный модуль?

2024-01-23 08:49 UTC, Aikeilol commented on packages/client/src/pages/Game/index.tsx
> +    return () => {
добавил

2024-01-23 08:49 UTC, Aikeilol commented on packages/client/src/pages/Game/index.tsx
> +  function getRandomInt(min: number, max: number) {
вынес

2024-01-23 09:06 UTC, zmenka approved these changes

2024-01-23 18:30 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    x: 160,
Лучше бы абстрагировать тут от размеров клеточек. Т.е. допустим поле 10х10. Координаты будут от 0 до 9. А потом уже клеточку легко привести в координаты. И можно будет легко сделать клеточку любого размера не меняя алгоритм игры а поменять лишь алгоритм отрисовки.

2024-01-23 18:32 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    const event = document.addEventListener('keydown', function (e) {
Метод addEventListener ничего не возвращает. Для отписки нужно сохранить функцию, которую подписали на событие, и использовать ее в методе removeEventListener

2024-01-23 18:33 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      if (e.which === 37 && snake.dx === 0) {
Согласен, это нужно доработать. Иначе не читается

2024-01-23 18:37 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    // Дальше будет хитрая функция, которая замедляет скорость игры с 60 кадров в секунду до 15. Для этого она пропускает три кадра из четырёх, то есть срабатывает каждый четвёртый кадр игры. Было 60
Обратите внимание - requestAnimationFrame не гарантирует 60 кадров в секунду. Количество кадров в секунду зависит от сложности и длительности того, что делается внутри функции отрисовки. Если вы хотите как-то зависеть от времени, то обратите внимание на первый аргумент, который приходит в функцию отрисовки.

2024-01-23 18:40 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    if (snake.cells.length > snake.maxCells) {
А почему только если длина превышает максимальную? Разве мы не должны на каждый шаг змеи убирать последнюю клетку (хвост)?

2024-01-23 18:44 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      for (let i = index + 1; i < snake.cells.length; i++) {
А зачем это делать для каждого элемента тела змеи? Достаточно же проверить только что голова есть где-то среди элементов кроме первого места. Сделать это можно один раз после того как все нарисовали. И наверное же надо какой-то экран показать что игра закончена а не начинать новую сразу?

2024-01-23 18:45 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +    }
Очистка ресурсов после разрушения компонента - лайк 👍

2024-01-23 18:47 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      if (cell.x === apple.x && cell.y === apple.y) {
Вот эта проверка тоже как-то не на месте. Мы же тело рисуем. Зачем на каждую клетку проверять встретились мы с яблоком или нет? Это надо проверить один раз после того как все нарисовали.

2024-01-23 18:49 UTC, Olegas requested changes
Добрый день.
Есть несколько замечаний по коду - написал подробные комментарии.
Еще я бы посоветовал выделить несколько более простых функций для типовых операций (сбросить состояние, добавить яблоко, нарисовать змею, проверить пересечение, проверить съедание яблока и т.п.) - так код основного алгоритма будет проще читаться. Еще можно выделить алгоритм игры в класс а функции разместить в методах.

2024-01-25 16:12 UTC, Olegas requested changes
Не все замечания исправлены (написал дополнительно какие именно). Нужно или исправить, или объяснить почему так правильно.

2024-01-25 16:12 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      if (cell.x === apple.x && cell.y === apple.y) {
Не исправлено. Это критичное замечание. Нужно либо исправить либо объяснить, почему так правильно

2024-01-25 16:12 UTC, Olegas commented on packages/client/src/pages/Game/index.tsx
> +      for (let i = index + 1; i < snake.cells.length; i++) {
Не исправлено. Это критичное замечание. Нужно либо исправить либо объяснить, почему так правильно

2024-01-25 18:58 UTC, Aikeilol commented on packages/client/src/pages/Game/index.tsx
> +      for (let i = index + 1; i < snake.cells.length; i++) {
Привет, задача на экран конца игры есть, но это не входит в задачу сделать игровой движок, поэтому этого экрана пока нет.
Что касается проверки, не совсем вас понимаю, я же в цикле как раз иду по всем элементам, кроме первого и сверяю их

2024-01-25 19:15 UTC, Aikeilol commented on packages/client/src/pages/Game/index.tsx
> +      for (let i = index + 1; i < snake.cells.length; i++) {
А, стоп, я понял, да ошибка достаточно критичная получается цикл в цикле сделал

2024-01-26 06:23 UTC, Olegas approved these changes
Работа принята.

Общая рекомендация - большие функции разбивать на более мелкие, так код будет лучше читаться. Например в блоке где ты понимаешь что змея съела саму себя блок сброса состояния игры можно вынести в функцию. Аналогично блок кода создания яблока в случайном месте тоже можно вынести т.к. он сейчас повторяется несколько раз.

Еще один совет, но это уже более сложный концепт - разделение кода. Вот представь что завтра у тебя в поле изменится количество клеточек. Или изменится размер клеточки (например для мобильного устройства решите сделать крупнее) - это приведет к внесению изменений в код механики игры что странно. Или другой пример - представь что завтра игру надо будет рисовать не на канвасе а например в 3D или через SVG или другие DOM-элементы. Или перепишем игру не на React, а на чем-то другом. Снова полезем в код механики игры. Почему? Потому что код механики игры не абстрагирован от рендеринга и представления, его деталей (размеры поля, размеры клеточки). В идеале алгоритм игровой механики должен быть отделен так, что бы смена представления и его характеристик привели к изменениям в коде представления а не в коде игровой механики.

2024-01-28 09:42 UTC, merged