Tea 25 --- Страница профиля
Aikeilol/team-project pull request #11
Opened 2024-01-26 19:12 UTC by Groghrus

1. Сверстать страницу профиля. 

2. Подключить API смены пароля

3. Сверстать компонент изменения аватара. 

4. Подключить API для смены аватара пользователя

P.S:  функционал общего компонента Form  будет дополнен после 6 спринта 

https://linear.app/team-project/issue/TEA-25/sverstat-stranicu-polzovatelya

2024-01-27 08:24 UTC, alraskalov commented on packages/client/src/pages/PasswordEdit/index.tsx
> +      type: 'password',
Лучше вынести данные для нового типа инпута в отдельную переменную в packages\client\src\components\Form\data.ts, и уже оттуда импортировать.

2024-01-27 08:24 UTC, alraskalov commented on packages/client/src/pages/PasswordEdit/index.tsx
> +      type: 'password',
Аналогично

2024-01-27 08:24 UTC, alraskalov commented on packages/client/src/pages/Profile/index.tsx
> +      type: 'text',
Тоже самое

2024-01-27 08:25 UTC, alraskalov commented on packages/client/src/pages/Settings/index.tsx
> +      type: 'text',
Аналогично

2024-01-27 08:26 UTC, alraskalov commented on packages/client/src/components/Profile/ProfileFooter/index.tsx
> +        color={"#FF0000"}
Возможно стоит вынести цвет в конфиг MUI Theme

2024-01-27 08:26 UTC, alraskalov commented on packages/client/src/components/Profile/ProfileFooter/index.tsx
> +        color={"#1C47BE"}
Возможно стоит вынести цвет в конфиг MUI Theme

2024-01-27 08:27 UTC, alraskalov commented on packages/client/src/components/Profile/ProfileFooter/index.tsx
> +        color={"#1C47BE"}
Возможно стоит вынести цвет в конфиг MUI Theme

2024-01-27 08:30 UTC, alraskalov reviewed
Так в целом, критических замечаний не вижу.

2024-01-27 10:38 UTC, alraskalov commented on packages/client/src/pages/PasswordEdit/index.tsx
> +  const data: IAuthData = {
Интерфейс IAuthData ожидает еще footerInfo, нужно его сделать необязательным, иначе TS ругается.
По хорошему бы конечно унифицировать названия интерфейсов, которые теперь используются и в форме регистрации/авторизации и в форме редактирования данных.

2024-01-27 13:50 UTC, Groghrus commented on packages/client/src/components/Profile/ProfileFooter/index.tsx
> +        color={"#FF0000"}
заменил на цвета из дефолтной палитры

2024-01-27 13:51 UTC, Groghrus commented on packages/client/src/components/Profile/ProfileFooter/index.tsx
> +        color={"#1C47BE"}
заменил на цвета из дефолтной палитры

2024-01-27 14:06 UTC, alraskalov approved these changes

2024-01-27 14:32 UTC, Olegas requested changes
Добрый день.
Основное замечание - все компоненты стилизуются через инлайновые стили, которые по сути пересоздаются на каждый рендер заново что приводит к смене пропсов дочерних компонентов. Выглядит как очень неэкономная в плане перерисовок реализация. Стили можно либо вынести за границы компонента либо мемоизировать. Либо воспользоваться старым добрым CSS )

2024-01-27 14:32 UTC, Olegas commented on packages/client/src/components/PasswordEdit/index.tsx
> +      }}
Значение свойства sx каждый раз разное. Надо вынести его за границу компонента что бы не влиять на перерисовку дочернего компонента

2024-01-27 14:32 UTC, Olegas commented on packages/client/src/components/Profile/ProfileHeader/index.tsx
> +    <>
Лишний Fragment (в нем всего один дочерний элемент)

2024-01-29 17:19 UTC, Olegas approved these changes
Добрый день.
Работу приму, но обрати внимание - много где стили по прежнему идут объектами. Я бы не рекомендовал на будущее злоупотреблять этим.

2024-01-30 14:08 UTC, merged