TEA-61 Добавить API для лидерборда.
Aikeilol/team-project pull request #23
Opened 2024-02-20 18:21 UTC by Groghrus

Добавил API для лидерборда.

2024-02-21 12:21 UTC, Groghrus commented on packages/client/src/pages/LeaderBord/index.tsx
> +      ratingFieldName: 'ratingSlytherinTeam',
тоже думал об этом

2024-02-22 09:23 UTC, kate-lozovaya requested changes
Оставила несколько комментариев. Из критичного - странный useEffect, проверь его, пожалуйста, и поправь

2024-02-22 09:23 UTC, kate-lozovaya commented on packages/client/src/components/Game/index.tsx
> +    }
[Исправление]
Значение `userData` поменяется только когда `useEffect` завершится. 
То есть при первом выполнении точно попадешь в `if` + `userData` должен быть в зависимостях `useEffect`, так как он используется в этом эффекте, сейчас зависимости выставлены некорректно, можно добавить правило `"react-hooks/exhaustive-deps": "warn",` в линтер.

Нужно выставить в `useEffect` корректные зависимости и разбить `getUser` и `addUserToLeaderBoard`.
Один эффект должен подтянуть юзера, а на изменения юзера должен происходить `addUserToLeaderBoard`

2024-02-22 09:23 UTC, kate-lozovaya commented on packages/client/src/components/LeaderBoard/LeaderBoardItem/index.tsx
> +          <Avatar src={`${API_URL}/resources${userAvatar}`} />
[Предложение]
Может сделать функцию в `utils` вроде `getImageSrc(что-то)` чтобы не хранить тут `${API_URL}/resources$`

2024-02-22 09:23 UTC, kate-lozovaya commented on packages/client/src/utils/scripts/api/leaderBoardApi.ts
> +    showAlert(message, 'error')
[Предложение]
Код для ошибки повторяется, можно вынести его в функцию

2024-02-23 19:34 UTC, kate-lozovaya approved these changes
👍🏻
лучше еще добавить в линтер правило про хуки, чтобы никогда не забывать никакие зависимости )

2024-02-27 09:03 UTC, merged