Настроить Express для Server Side Rendering (без Redux)
Aikeilol/team-project pull request #24
Opened 2024-02-23 13:11 UTC by feihoa

Настроила Express для Server Side Rendering
Для локального запуска нужно создать ссылку на клиент в папке с клиентом командой yarn link, а затем в директории сервера командой yarn link client создать связь между двумя директориями
Команда yarn build в клиентской директории создаст папки dist и dist-ssr с клиентскими сборками
Команда yarn build в серверной директории создаст папку dist для сервера, после чего командой yarn preview запускается сервер на порту 3001
<img width="926" alt="image" src="https://github.com/Aikeilol/team-project/assets/63012945/f322815a-1a54-40bb-93dc-bd96f349f23f">

2024-02-23 16:28 UTC, Groghrus approved these changes
Критических замечаний нет, все работает как описано в инструкции.

2024-02-23 16:28 UTC, Groghrus commented on packages/client/package.json
>      "preview": "vite preview",
Я бы добавил в scripts  в package.json клиента и сервера команду yarn link и yarn link client соответственно.

2024-02-24 13:10 UTC, zmenka commented on packages/client/src/components/Game/constants.ts
> +const isSSR = typeof document === 'undefined'
Надо бы унести в отдельные константы, эти чисто про игру. А isSSR про само прилоежние

2024-02-26 07:58 UTC, Olegas requested changes
Добрый день.
Странная проверка на isSSR в коде приложения. По идее такого быть не должно. В коде рендеринга - возможно, но не дальше в приложении.
Надо доработать.

2024-02-26 07:58 UTC, Olegas commented on packages/client/src/components/Game/constants.ts
> +}
А зачем так делать? Это же получается спрайты будут созданы вообще в момент старта приложения (когда бандл заимпортируется). Не надо просто такую предзагрузку делать и проверка тогда не понадобится.

2024-02-26 16:22 UTC, Olegas approved these changes
Работа принята

2024-02-26 17:00 UTC, merged