Добавить ещё одно WEB API (Notification API +  Media Api)
Aikeilol/team-project pull request #25
Opened 2024-02-25 00:52 UTC by zmenka

Добавлено Notification API - при окончании игры появляется нотификация с очками и личным рекордом

<img width="414" alt="Screenshot 2024-02-25 at 01 55 14" src="https://github.com/Aikeilol/team-project/assets/5979721/932aa7ca-917b-4c20-840a-357bcab2bb26">

Добавлено Media Api - звуки в игре
- звук при нажатиях на стрелки
- звук при съедании змейкой яблока
- звук при окончании игры

Поиграть можно [здесь](https://team-project-client-git-main-zmenka1s-projects.vercel.app/game)

2024-02-26 10:44 UTC, khitrind requested changes
Привет по коду все выглядит не плохо, но стоит его немного подготовить к ssr (в комментариях расписал подробнее).

2024-02-26 10:44 UTC, khitrind commented on packages/client/src/utils/notifications/index.ts
> +  }
1)  Кажется тут стоит выбрать что-то одно. Когда мы определяем функцию асинхронной, она по умолчанию возвращает промис, не нужно писать await. (await  в таком формате нужен только если есть обертка try{}catch, в ином случае просто получаем лишний врапер [вот тут неплохо описано](https://jakearchibald.com/2017/await-vs-return-vs-return-await/)).

 В вашем же случае будет нагляднее либо убрать async и просто вернуть 
`return Notification.requestPermission()....`
Или использовать уже async/await синтаксис.

2) Есть ли какая-то логика на случай ошибки?

2024-02-26 10:44 UTC, khitrind commented on packages/client/src/utils/notifications/index.ts
> +  alreadyRequested = false
Идея отслеживать, был ли уже запрошен доступ к уведомлениям, кажется полезной, но в текущей реализации она не полностью решает проблему. Браузеры обычно сами управляют поведением запросов на разрешения, и этот флаг не будет иметь большого эффекта на поведение браузера.

2024-02-27 11:30 UTC, khitrind requested changes
Привет по коду все выглядит не плохо, но стоит его немного подготовить к ssr (в комментариях расписал подробнее).

2024-02-27 11:30 UTC, khitrind requested changes
Привет по коду все выглядит не плохо, но стоит его немного подготовить к ssr (в комментариях расписал подробнее).

2024-02-28 17:17 UTC, khitrind approved these changes
Кое что нужно доработать, но думаю смысла +- понятен, работу принимаю что бы не тормозить сдачу проекта)

2024-02-28 17:17 UTC, khitrind commented on packages/client/src/App.tsx
> +import React, { StrictMode } from 'react'
Импорт стоит удалить, если он не используется (за тикими штуками стоит следить [литером](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-unused-vars.md))

2024-02-28 17:17 UTC, khitrind commented on packages/client/src/context/AppContext/index.ts
> +
Тут снова получается один инстанс. Кусочек про new Notifications() стоит вынести в entry-client.

Можно отсюда экспортировать функцию:

```
export const createAppContext = () => ({notifications: new Notifications()});

И внутри entry-client ее вызывать и передвать результата как проп:

export type AppContextType = {
  notifications: Notifications
}

export const createAppContext = () => ({
  notifications: new Notifications(),
})

export const AppContext = createContext<AppContextType | null>(null)

type Props = {
  value: AppContextType
}

export const AppContextProvider = ({ children, value }: PropsWithChildren<Props>) => (
  <AppContext.Provider value={value}>{children}</AppContext.Provider>
)

export const useAppContext = () => {
  const context = useContext(AppContext)

  if (!context) {
    throw new Error('useAppContext must be used within a AppContextProvider')
  }

  return context
}

const appContext = createAppContext()

const App = () => (
  <AppContextProvider value={appContext}>
    <div>App</div>
  </AppContextProvider>
)

```

2024-02-28 19:07 UTC, zmenka commented on packages/client/src/context/AppContext/index.ts
> +
Все равно до конца не могу понять, как это подружить с ssr((  
Ведь если я не оборачиваю App в AppContextProvider в entry-server.tsx, то у меня как раз сработает эта ошибка на отсутствие контекста при первой загрузке страницы с игрой. Не могли бы вы пояснить, как это можно решить?

2024-02-29 08:21 UTC, khitrind commented on packages/client/src/context/AppContext/index.ts
> +
App в целом должен быть завернут во все контексты, просто создание его наполнения должно быть не:

`export someClass = new SomeClass();` из модуля, потому что так он один раз при ssr  создастся и будем переиспользован при каждом запросе. А это должна быть функция которая создает инстанс.  И вызов этой функции должен быть внутри клиентского энтри. 
В серверном энтри можно передать мок.

2024-02-29 10:04 UTC, zmenka commented on packages/client/src/context/AppContext/index.ts
> +
Спасибо, теперь понятно

2024-02-29 12:42 UTC, merged